version: '3.7'
services:
  database:
    container_name: db-postgres
    image: postgres:10.17
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=worldcup
    volumes:
      - ./scriptWorldCup.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5441:5432

  app:
    container_name: api-node
    image: node:alpine
    restart: always
    depends_on:
      - database
    ports:
      - 8087:8087
    volumes:
      - ./api:/app
    working_dir: /app
    command: npm start
